#!/bin/bash
#    __
#   / /_  _________ _      ______ ___
#  / __ \/ ___/ __ \ | /| / / __ `__ \
# / /_/ (__  ) /_/ / |/ |/ / / / / / /
#/_.___/____/ .___/|__/|__/_/ /_/ /_/
#          /_/
#		Edited by @aguilluy, from:   https://github.com/sk1lax/bspwm-dots
#

#*****----- Workspaces -----*****
bspc monitor -d 'I' 'II' 'III' 'IV' 'V' 'VI' 'VII' 'VIII' 'IX' 'X' &

#*****----- BSPWM Launch -----*****
export XDG_CURRENT_DESKTOP='bspwm'

# Ejecutar programas al inicio
pgrep -x sxhkd > /dev/null || sxhkd &
feh --no-fehbg --bg-fill /home/andrew/Desktop/Fondos/fondo.jpg & # Fondo actualizado
picom & # Compositor
cvlc -vvv --daemon --extraintf rc --rc-unix ~/.config/vlc/vlc.sock & # Demonio VLC
alsa & # Control de sonido
~/.config/polybar/launch.sh & # Script adicional de inicio

# Regla para forzar mensajes yad flotantes
bspc rule -a yad state=floating

# Regla para fijar la polibar (Dedicated Window Class)
bspc rule -a polybar:Polybar floating=on sticky=on above=on &

#*****----- Window Gaps -----*****
##bspc config gapless_monocle false &
bspc config window_gap 6 & 

#*****----- Window Borders -----*****
bspc config border_width 0 & 

#*****----- Fix Pointer -----*****
xsetroot -cursor_name left_ptr &

#*****----- BSPWM Configs -----*****
bspc config top_padding 45 & # This setting I only used to avoid overlaping with polybar.
bspc config focus_follows_pointer true &
bspc config pointer_modifier super &
bspc config pointer_action1 move &
bspc config pointer_action2 resize_side &
bspc config pointer_action3 resize_corner &

#*****----- Monocle and Split Configuration -----*****
##bspc config single_monocle true &
bspc config gapless_monocle true & # Aseguramos que no haya gaps en monocle
bspc config paddingless_monocle true &
bspc config borderless_monocle true &
bspc config split_ratio 0.52 & # Ajustado a tu preferencia

#*****----- Configuración de Organización entre Ventanas -----*****
##bspc config automatic_scheme longest_side
##bspc config initial_polarity second_child
##bspc config removal_adjustment true

pgrep -x cvlc > /dev/null && echo "cvlc is running" || echo "cvlc is not running" >> ~/.config/vlc/cvlc.log
wmname LG3D &
